<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Complaint;

class ComplaintSeeder extends Seeder
{
    public function run(): void
    {
        $complaints = [
            "General weakness",
            "Fatigue",
            "Dizziness",
            "Fainting episode",
            "Weight loss",
            "Weight gain",
            "Loss of appetite",
            "Excessive sweating",
            "Night sweats",
            "Fever",
            "Fever with chills",
            "Recurrent fever",
            "Chills and rigors",
            "Back pain",
            "Low back stiffness",
            "Neck pain",
            "Shoulder pain",
            "Joint pain",
            "Morning stiffness",
            "Joint swelling",
            "Crepitus",
            "Reduced joint movement",
            "Difficulty climbing stairs",
            "Muscle pain",
            "Muscle cramps",
            "Weakness while walking",
            "Loss of height",
            "Stooped posture",
            "Bone pain",
            "Fracture after minor fall",
            "Joint deformity",
            "Work-related body pain",
            "Dry cough",
            "Productive cough",
            "Shortness of breath",
            "Breathlessness on exertion",
            "Chest pain",
            "Chest tightness",
            "Wheezing",
            "Blood in sputum",
            "Recurrent respiratory infections",
            "Sore throat",
            "Runny nose",
            "Sneezing",
            "Nasal congestion",
            "Throat irritation",
            "Watery eyes",
            "Headache",
            "Red eye",
            "Eye pain",
            "Eye discharge",
            "Blurred vision",
            "Foreign body in eye",
            "Ear pain",
            "Ear discharge",
            "Reduced hearing",
            "Hearing loss",
            "Tinnitus",
            "Nose bleeding",
            "Upper abdominal pain",
            "Lower abdominal pain",
            "Abdominal distension",
            "Bloating",
            "Nausea",
            "Vomiting",
            "Diarrhoea",
            "Constipation",
            "Blood in stool",
            "Black stool",
            "Worm infestation",
            "Anal itching",
            "Piles symptoms",
            "Heartburn",
            "Acid regurgitation",
            "Sour taste in mouth",
            "Difficulty swallowing",
            "Chronic cough (GERD related)",
            "Itching",
            "Skin redness",
            "Dry skin",
            "Circular red rash",
            "Burning sensation",
            "Skin thickening",
            "Heel cracks",
            "White depigmented patches",
            "Red scaly plaques",
            "Boils",
            "Skin abscess",
            "Non-healing wound",
            "Fungal infection",
            "Bacterial skin infection",
            "Mouth ulcers",
            "Pain while eating",
            "Cracked lips",
            "Toothache",
            "Dental caries",
            "Bleeding gums",
            "Vertigo",
            "Imbalance",
            "Numbness in feet",
            "Tingling sensation",
            "Burning urination",
            "Frequent urination",
            "Blood in urine",
            "Leg swelling",
            "Irregular menstruation",
            "Heavy menstrual bleeding",
            "Missed periods",
            "Vaginal discharge",
            "Breast pain",
            "Breast lump",
            "Morning sickness",
            "Poor weight gain in child",
            "Delayed milestones",
            "Loss of fetal movements",
            "High blood sugar symptoms",
            "High blood pressure symptoms",
            "Non-healing foot ulcer",
            "Sleep disturbance",
            "Anxiety symptoms",
            "Low mood",
            "Irritability",
            "Poor concentration",
            "Fever with rash",
            "Fever with joint pain",
            "Suspected malaria symptoms",
            "Suspected dengue symptoms",
            "Suspected typhoid symptoms",
            "Cosmetic concern",
            "General health check-up",
            "Follow-up visit",
            "Medication refill request"
        ];

        foreach ($complaints as $complaint) {
            Complaint::create([
                'complaint' => $complaint
            ]);
        }
    }
}